### ISSUE TITLE
not working please read

### ISSUE THREAD

**Issue by wass-cscn** [efenatuyo/case-opening-simulator-2-script#1]
people tryna "fix" ur code and reselling it if u want i can host it for u and make it free for everyone i tried modding the src but it didnt work so ill hope that u fix the script or just reach me at Peek#3055 on discord i sent u a friend request btw

**Comment by wass-cscn** [comment]
@efenatuyo

**Comment by efenatuyo** [comment]
Hi

**Comment by efenatuyo** [comment]
Reach me over discord.gg/xolo

**Comment by wass-cscn** [comment]
Ur old acc got termed by discord could you add me again at wass#2611 cuz I need help with the script as an update broke it and I’ve been tryna fix it by myself

**Comment by efenatuyo** [comment]
ok xolo#6826
